# Treinamento Nextflow

## Visão geral do curso

Este curso é divido em duas partes, no primeiro momento veremos como o nextflow é estruturado e no segundo momento aprenderemos a executar e personalizar pipelines já existentes. Cada sessão possui objetivos estruturados para introduzir informações gradualmente.

# Ambiente de trabalho

## Ambiente Local

Caso todas as dependencias necessárias para execução desse minicurso estejam instaladas em sua máquina local, clone o repositório deste minicurso:

```{bash}
git clone git@github.com:dalmolingroup/nextflow_training.git

cd nextflow_training
```

## Ambiente Remoto

Caso não as dependencias necessárias para este minicurso não estejam instaladas na sua máquina local, você poderá utilizar o ambiente pré-construído fornecido pela Seqera no [GitHub Codespace](https://codespaces.new/nextflow-io/training?quickstart=1&ref=3.6.1). Este ambiente de treinamento contém todo o software, código e dados necessários para trabalhar no curso de treinamento, então você não precisa instalar nada por conta própria.

# Objetivos